{
  "differencing_disk": "false",
  "firmware": "",
  "iso_checksum_type": "",
  "vm_name": "",
  "os_build_type": "\"\"",
  "enable_secure_boot": "true",
  "unattend_file": "",
  "build_type": "",
  "enable_dynamic_memory": "false",
  "skip_compaction": "false",
  "switch_name": "Default Switch",
  "os_name": "",
  "keep_registered": "false",
  "winrm_username": "itadm",
  "generation": "2",
  "http_port_min": "8000",
  "iso_checksum": "",
  "winrm_password": "itadm",
  "disk_size": "40960",
  "shutdown_timeout": "4h",
  "http_directory": "",
  "skip_export": "false",
  "output_directory": "",
  "use_fixed_vhd_format": "false",
  "memory": "2048",
  "secondary_iso_images": "",
  "use_legacy_network_adapter": "false",
  "http_port_max": "9000",
  "disk_block_size": "32",
  "cpus": "2",
  "enable_mac_spoofing": "false",
  "communicator": "winrm",
  "enable_virtualization_extensions": "false",
  "shutdown_command": "null",
  "iso_url": "",
  "headless": "true"
}
