{
  "disk_size": "40960",
  "keep_registered": "false",
  "communicator": "winrm",
  "winrm_username": "itadm",
  "winrm_password": "itadm",
  "winrm_insecure": "true",
  "use_legacy_network_adapter": "false",
  "differencing_disk": "false",
  "use_fixed_vhd_format": "false",
  "disk_block_size": "32",
  "memory": "2048",
  "switch_name": "Default Switch",
  "cpus": "2",
  "generation": "2",
  "enable_mac_spoofing": "false",
  "enable_dynamic_memory": "false",
  "enable_secure_boot": "true",
  "enable_virtualization_extensions": "false",
  "skip_compaction": "false",
  "skip_export": "false",
  "headless": "true",
  "http_directory": "null",
  "http_port_min": "8000",
  "http_port_max": "9000",
  "shutdown_command": "null",
  "shutdown_timeout": "4h",
  "winrm_port": "5985",
  "winrm_use_ssl": "false",
  "winrm_timeout": "2h",
  "winrm_use_ntlm": "true"
}