{
  "enable_virtualization_extensions": "false",
  "unattend_file": "H:\\PackerShell\\windows\\unattend\\uefi\\ENTERPRISE\\autounattend.xml",
  "enable_dynamic_memory": "false",
  "keep_registered": "false",
  "enable_mac_spoofing": "false",
  "cpus": "2",
  "winrm_username": "itadm",
  "use_fixed_vhd_format": "false",
  "secondary_iso_images": "H:\\PackerShell\\windows\\unattend\\uefi\\ENTERPRISE\\answer.iso",
  "shutdown_command": "null",
  "http_port_min": "8000",
  "memory": "2048",
  "iso_url": "H:\\PackerShell\\shared\\http\\iso\\windows-1909.3.2020-desktop-x64.iso",
  "communicator": "winrm",
  "output_directory": "H:\\PackerShell\\builds\\packer-windows-1909.3.2020-desktop-x64\\{{.Provider}}",
  "iso_checksum_type": "file",
  "firmware": "uefi",
  "enable_secure_boot": "true",
  "iso_checksum": "H:\\PackerShell\\shared\\http\\iso\\checksums\\windows-1909.3.2020-desktop-x64_checksum.txt",
  "os_name": "windows",
  "os_build_type": "desktop",
  "generation": "2",
  "http_directory": "H:\\PackerShell\\shared\\http",
  "shutdown_timeout": "4h",
  "differencing_disk": "false",
  "http_port_max": "9000",
  "vm_name": "packer-windows-1909.3.2020-desktop-x64",
  "build_type": "",
  "skip_export": "false",
  "disk_block_size": "32",
  "skip_compaction": "false",
  "disk_size": "40960",
  "headless": "true",
  "use_legacy_network_adapter": "false",
  "switch_name": "Default Switch"
}
