{
  "os_build_type": "desktop",
  "keep_registered": "",
  "use_fixed_vhd_format": "",
  "disk_size": "",
  "switch_name": "",
  "enable_dynamic_memory": "",
  "skip_export": "",
  "headless": "",
  "vm_name": "packer-windows-1909.3.2020-desktop-x64",
  "build_type": "",
  "shutdown_command": "",
  "generation": "",
  "firmware": "uefi",
  "iso_checksum_type": "file",
  "memory": "",
  "enable_mac_spoofing": "",
  "enable_secure_boot": "",
  "os_name": "windows",
  "enable_virtualization_extensions": "",
  "http_port_max": "",
  "http_port_min": "",
  "output_directory": "E:\\SIUCPacker\\builds\\packer-windows-1909.3.2020-desktop-x64\\{{.Provider}}",
  "iso_checksum": "\"{{ .HTTPIP }}\":\"{{ .HTTPPort }}\"/iso/checksums/windows-1909.3.2020-desktop-x64_checksum.txt",
  "communicator": "",
  "skip_compaction": "",
  "use_legacy_network_adapter": "",
  "shutdown_timeout": "",
  "winrm_username": "",
  "unattend_file": "E:\\SIUCPacker\\windows\\unattend\\uefi\\ENTERPRISE\\autounattend.xml",
  "iso_url": "E:\\SIUCPacker\\shared\\http\\iso\\windows-1909.3.2020-desktop-x64.iso",
  "differencing_disk": "",
  "http_directory": "E:\\SIUCPacker\\shared\\http",
  "cpus": "",
  "disk_block_size": ""
}
